# Generated by Django 4.1.4 on 2023-01-26 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_user_follows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='like',
        ),
    ]
