# Generated by Django 4.1.4 on 2023-01-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_remove_user_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cont',
            field=models.TextField(blank=True),
        ),
    ]
